language: ruby

cache: bundler

rvm:
  - 2.7.1
  - 2.6.6
  - 2.5.8
  - 2.4.10
  - ruby-head
  - jruby-9.2.13.0
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.2.13.0
    - rvm: jruby-head

before_install:
  - gem update bundler

deploy:
  provider: rubygems
  api_key:
    secure: fB7mDtkzL6Atv3/fkCion1NOwDlls5RxdoLrKIKyK4G6QFr2Py8Ijj/oY3i/xkOdo8O6qIE+wFZhzlGZZFBSWJijYWzrQ2FJu3W5oDUtN5ybZUfZbEchCwRXBOA++d5toFXBmEI7P3XTWiLiBmnmAgK2T7MNaeI2MbjIp8BUYXc=
  gem: omniauth-artsy
  on:
    tags: true
    repo: artsy/omniauth-artsy
  skip_cleanup: 'true'
