language: ruby

cache: bundler

rvm:
  - 2.6.0
  - 2.5.3
  - 2.4.4
  - jruby-9.2.5.0
  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.2.5.0
    - rvm: jruby-head

before_install:
  - gem update bundler
