language: ruby

cache: bundler

rvm:
  - 2.3.0
  - 2.2
  - rbx-2
  - jruby-19mode
  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: ruby-head
    - rvm: jruby-head

before_install:
  - gem update bundler
